resolver: lts-8.13

packages:
- libs/bilge
- libs/brig-types
- libs/cargohold-types
- libs/cassandra-util
- libs/galley-types
- libs/gundeck-types
- libs/http-client-openssl-ext
- libs/metrics-collectd
- libs/metrics-core
- libs/metrics-wai
- libs/ropes
- libs/sodium-crypto-sign
- libs/tasty-cannon
- libs/types-common
- libs/types-common-journal
- libs/wai-utilities
- libs/zauth
- services/brig
- services/cannon
- services/cargohold
- services/galley
- services/gundeck
- services/proxy
- tools/bonanza
- tools/makedeb
- location:
    git: https://github.com/tiago-loureiro/haskell-multihash.git
    commit: 10a0d7d765d87fa937fafa42ee7a45f871c9758e
  extra-dep: true
- location:
    git: https://github.com/wireapp/cryptobox-haskell
    commit: 7546a1a25635ef65183e3d44c1052285e8401608
  extra-dep: true
- location:
    git: https://github.com/kim/hs-collectd
    commit: '0.0.0.1'
  extra-dep: true

extra-deps:
- aws-0.16
- base58-bytestring-0.1.0
- bloodhound-0.13.0.0
- data-timeout-0.3
- geoip2-0.2.2.0
- html-entities-1.1.4.1
- mime-0.4.0.2
- snappy-0.2.0.2
- snappy-framing-0.1.1
- text-icu-translit-0.1.0.7
- wai-middleware-gunzip-0.0.2
- websockets-0.11.2.0

flags:
  types-common:
    cql: True
    protobuf: True
    arbitrary: True

extra-package-dbs: []

